name: Build
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@831cdfeaf21957af495b3d518c1a877d5ffd3253 # v2.1.1
  build:
    name: Build (Node.js ${{ matrix.nodeVersion }})
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: [18, 19]
    uses: vidavidorra/.github/.github/workflows/node-build.yml@831cdfeaf21957af495b3d518c1a877d5ffd3253 # v2.1.1
    with:
      nodeVersion: ${{ matrix.nodeVersion }}
  release:
    needs: [lint, build]
    runs-on: ubuntu-latest
    # GitHub API requests can easy take a couple of seconds and the release can
    # make lots of API requests when a release has a lot of commits. If every
    # requests takes five seconds, which is on the high side for a request, this
    # could perform 180 requests. This should be enough for most use cases.
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
      - name: Install project
        run: npm ci --ignore-scripts
      - name: GitHub App token
        id: app-token
        uses: vidavidorra/github-app-token@e1df6ef2d28f0b02c63c7e9446e12547584f17fe # v1.0.0
        with:
          appId: ${{ secrets.RELEASE_APP_ID }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
          includeUserInformation: true
      - name: Release
        env:
          DOCKER_REGISTRY_USER: ${{ vars.GH_PACKAGES_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GH_PACKAGES_TOKEN }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          GIT_AUTHOR_NAME: ${{ steps.app-token.outputs.username }}
          GIT_AUTHOR_EMAIL: ${{ steps.app-token.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.app-token.outputs.username }}
          GIT_COMMITTER_EMAIL: ${{ steps.app-token.outputs.email }}
        run: npx --no-install semantic-release
