name: Lint commit messages
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@9dde233ec4ff195ad50eebd5bd7ea80deed9cf35 # v4.1.9
    with:
      configFile: package.json
