name: Lint commit messages
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@8ff206f1ac194e50cfc4847a9786641d22dd1f42 # v4.1.8
    with:
      configFile: package.json
