name: Lint commit messages
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@0d26596b8ec32cde40a2c8f96e73d4073e6a7be2 # v4.1.6
    with:
      configFile: package.json
