name: Lint commit messages
on:
  push:
    branches:
      - main
      - beta
      - 'renovate/**'
      - 'github-renovate/**'
  pull_request:
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@430b5f02ffe77661ce0fe69608df20e1eb478c95 # v4.1.1
    with:
      configFile: package.json
